wmusersnap.settings:
    type: config_object
    label: Settings
    mapping:
        api_key:
            type: string
            label: 'API key'
        enable:
            type: string
            label: 'Enable the integration'
        cookie_domain:
            type: string
            label: 'The domain on which the cookie will be set.'
            nullable: true
        domains:
            type: sequence
            label: 'A list of domains on which to enable the integration.'
            sequence:
                type: string
                label: 'Class name'
            nullable: true
        remove_cookie_on_logout:
            type: boolean
            label: 'Remove cookie after logging out'
